### ISSUE TITLE
Backend do Agendamento

### ISSUE THREAD

**Issue by hi-hi-ray** [Infnet-SJ90/infnet-sj90.github.io#7]
Ref: #4

To Do
- [x] Reproduzir o design.  [@larismourullo - está responsável por essa parte devido a possibilidade de fazer magia negra vulgo css]
- [x] Criar interação.
- [ ] Conexão com o Banco de Dados. 
- [ ] Validação do formulário.

**Comment by hi-hi-ray** [comment]
@larismourullo Terminou de fazer a reprodução do css?

**Comment by larismourullo** [comment]
@hi-hi-ray sim 👍
